# This file contains values from Cookiecutter

default_context:
  project_name: "jackson_job_shop_scheduling"
  project_description: "Implementation of a mathematical model in Python to solve an assignment problem in Job Shop environments. With its respective Gantt chart."
  organization: "PolyMtl"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.7
  github_name: "th-rpy"
  email: "thamer.saraei@polymtl.ca"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
